version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/mongodb/db:/data/db
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    environment:
      - "MONGO_INITDB_DATABASE=${MONGO_DB}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}"
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 1
    restart: unless-stopped
    command: mongod --quiet --logpath /dev/null
  bot:
    container_name: justBot
    build:
      context: ./bot
      dockerfile: Dockerfile
    env_file:
      - .env

volumes:
  logs: